apiVersion: v1
kind: Service
metadata:
  name: {{ template "aleiye.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 7777
      targetPort: 7777
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "aleiye.name" . }}
    release: "{{ .Release.Name }}"

